/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UvjetiKoristenjaRouteImport } from './routes/uvjeti-koristenja'
import { Route as TimRouteImport } from './routes/tim'
import { Route as SloziPcRouteImport } from './routes/slozi-pc'
import { Route as RecenzijeRouteImport } from './routes/recenzije'
import { Route as PolitikaPrivatnostiRouteImport } from './routes/politika-privatnosti'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const UvjetiKoristenjaRoute = UvjetiKoristenjaRouteImport.update({
  id: '/uvjeti-koristenja',
  path: '/uvjeti-koristenja',
  getParentRoute: () => rootRouteImport,
} as any)
const TimRoute = TimRouteImport.update({
  id: '/tim',
  path: '/tim',
  getParentRoute: () => rootRouteImport,
} as any)
const SloziPcRoute = SloziPcRouteImport.update({
  id: '/slozi-pc',
  path: '/slozi-pc',
  getParentRoute: () => rootRouteImport,
} as any)
const RecenzijeRoute = RecenzijeRouteImport.update({
  id: '/recenzije',
  path: '/recenzije',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitikaPrivatnostiRoute = PolitikaPrivatnostiRouteImport.update({
  id: '/politika-privatnosti',
  path: '/politika-privatnosti',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/faq': typeof FaqRoute
  '/kontakt': typeof KontaktRoute
  '/politika-privatnosti': typeof PolitikaPrivatnostiRoute
  '/recenzije': typeof RecenzijeRoute
  '/slozi-pc': typeof SloziPcRoute
  '/tim': typeof TimRoute
  '/uvjeti-koristenja': typeof UvjetiKoristenjaRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/faq': typeof FaqRoute
  '/kontakt': typeof KontaktRoute
  '/politika-privatnosti': typeof PolitikaPrivatnostiRoute
  '/recenzije': typeof RecenzijeRoute
  '/slozi-pc': typeof SloziPcRoute
  '/tim': typeof TimRoute
  '/uvjeti-koristenja': typeof UvjetiKoristenjaRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/faq': typeof FaqRoute
  '/kontakt': typeof KontaktRoute
  '/politika-privatnosti': typeof PolitikaPrivatnostiRoute
  '/recenzije': typeof RecenzijeRoute
  '/slozi-pc': typeof SloziPcRoute
  '/tim': typeof TimRoute
  '/uvjeti-koristenja': typeof UvjetiKoristenjaRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/faq'
    | '/kontakt'
    | '/politika-privatnosti'
    | '/recenzije'
    | '/slozi-pc'
    | '/tim'
    | '/uvjeti-koristenja'
    | '/blog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/faq'
    | '/kontakt'
    | '/politika-privatnosti'
    | '/recenzije'
    | '/slozi-pc'
    | '/tim'
    | '/uvjeti-koristenja'
    | '/blog/$slug'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/faq'
    | '/kontakt'
    | '/politika-privatnosti'
    | '/recenzije'
    | '/slozi-pc'
    | '/tim'
    | '/uvjeti-koristenja'
    | '/blog/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  FaqRoute: typeof FaqRoute
  KontaktRoute: typeof KontaktRoute
  PolitikaPrivatnostiRoute: typeof PolitikaPrivatnostiRoute
  RecenzijeRoute: typeof RecenzijeRoute
  SloziPcRoute: typeof SloziPcRoute
  TimRoute: typeof TimRoute
  UvjetiKoristenjaRoute: typeof UvjetiKoristenjaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uvjeti-koristenja': {
      id: '/uvjeti-koristenja'
      path: '/uvjeti-koristenja'
      fullPath: '/uvjeti-koristenja'
      preLoaderRoute: typeof UvjetiKoristenjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tim': {
      id: '/tim'
      path: '/tim'
      fullPath: '/tim'
      preLoaderRoute: typeof TimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slozi-pc': {
      id: '/slozi-pc'
      path: '/slozi-pc'
      fullPath: '/slozi-pc'
      preLoaderRoute: typeof SloziPcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recenzije': {
      id: '/recenzije'
      path: '/recenzije'
      fullPath: '/recenzije'
      preLoaderRoute: typeof RecenzijeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politika-privatnosti': {
      id: '/politika-privatnosti'
      path: '/politika-privatnosti'
      fullPath: '/politika-privatnosti'
      preLoaderRoute: typeof PolitikaPrivatnostiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  FaqRoute: FaqRoute,
  KontaktRoute: KontaktRoute,
  PolitikaPrivatnostiRoute: PolitikaPrivatnostiRoute,
  RecenzijeRoute: RecenzijeRoute,
  SloziPcRoute: SloziPcRoute,
  TimRoute: TimRoute,
  UvjetiKoristenjaRoute: UvjetiKoristenjaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
